/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cliente;
import Model.Comanda;
import Model.GerenciadordeComanda;
import Model.GerenciadordeUsuario;
import Model.Pedido;
import Model.Persistencia;
import Model.Produto;
import Model.Service;
import com.ufsc.comandasdebaresbigdinner.MiniControl;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class EnhancedMenuOpcoes extends javax.swing.JFrame {

    MiniControl mini;
    CardLayout cardlayout;

    /**
     * Creates new form EnhancedMenuOpcoes
     */
    public EnhancedMenuOpcoes() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(470, 485);
        mini = new MiniControl();
        jLabel2.setText(mini.getLastLogged().getNome());
        cardlayout = (CardLayout) jPanel3.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olá!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(339, 330));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel1.setText("Bem vindo, ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant-cutlery-circular-symbol-of-a-spoon-and-a-fork-in-a-circle2.png"))); // NOI18N
        jLabel3.setToolTipText("E.g.: Icon made by Freepik from www.flaticon.com ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 20);
        jPanel1.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanel1);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(6, 51));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(665, 69));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-new-document.png"))); // NOI18N
        jLabel11.setText("Abrir Comanda");
        jLabel11.setToolTipText("E.g.: Icon made by Sarfraz Shoukat from www.flaticon.com ");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator5);

        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart.png"))); // NOI18N
        jLabel12.setText("Adicionar pedido");
        jLabel12.setToolTipText("E.g.: Icon made by Google from www.flaticon.com ");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel12);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator6);

        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jLabel13.setText("Cancelar Pedido");
        jLabel13.setToolTipText("E.g.: Icon made by Eleonor Wang from www.flaticon.com ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel13);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator8);

        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credit-card.png"))); // NOI18N
        jLabel14.setText("Receber Pagamento");
        jLabel14.setToolTipText("E.g.: Icon made by Dave Gandy from www.flaticon.com ");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel14);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator9);

        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock.png"))); // NOI18N
        jLabel15.setText("Fechar Comanda");
        jLabel15.setToolTipText("E.g.: Icon made by Those Icons from www.flaticon.com ");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel15);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator10);

        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye-close-up.png"))); // NOI18N
        jLabel16.setText("Visualizar Comanda");
        jLabel16.setToolTipText("E.g.: Icon made by Freepik from www.flaticon.com ");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16);

        jScrollPane1.setViewportView(jPanel5);

        getContentPane().add(jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel18.setBackground(new java.awt.Color(204, 204, 255));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.Y_AXIS));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("    ");
        jPanel18.add(jLabel33);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("    ");
        jPanel18.add(jLabel34);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Selecione uma ação acima!");
        jPanel18.add(jLabel9);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("    ");
        jPanel18.add(jLabel30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Seja gentil com o cliente! ");
        jPanel18.add(jLabel19);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("    ");
        jPanel18.add(jLabel31);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Um ótimo trabalho!!");
        jPanel18.add(jLabel20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("    ");
        jPanel18.add(jLabel32);

        jPanel3.add(jPanel18, "card9");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Abrir Comanda");
        jPanel8.add(jLabel4);

        jPanel2.add(jPanel8);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel5.setText("NOME-CLIENTE");
        jPanel6.add(jLabel5);

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Nome do cliente");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel6.add(jTextField1);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setText("MESA");
        jPanel6.add(jLabel6);

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Mesa do cliente");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel6.add(jTextField2);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setText("                                                ");
        jPanel7.add(jLabel8);

        jButton1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jButton1.setText("Criar comanda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jPanel2.add(jPanel7);

        jPanel3.add(jPanel2, "card2");

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("Adicionar pedido");
        jPanel14.add(jLabel17);

        jPanel9.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(204, 204, 255));

        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Número da mesa");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um pedido", "X-Burger", "X-Salada", "Iscas de Frango", "Cerveja", "Suco", "Couvert artístico" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jTextPane1.setEditable(false);
        jScrollPane3.setViewportView(jTextPane1);

        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Número da mesa");

        jLabel39.setForeground(new java.awt.Color(0, 153, 0));
        jLabel39.setText("Quantidade");

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel39)
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(0, 279, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel9.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(204, 204, 255));

        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton2);

        jPanel9.add(jPanel16);

        jPanel3.add(jPanel9, "card3");

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jPanel22.setBackground(new java.awt.Color(204, 204, 255));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setText("Cancelar Pedido");
        jPanel22.add(jLabel22);

        jPanel10.add(jPanel22);

        jPanel19.setBackground(new java.awt.Color(204, 204, 255));
        jPanel19.setLayout(new java.awt.GridBagLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido a remover", "X-Burger", "X-Salada", "Iscas de Frango", "Cerveja", "Suco", "Couvert artístico" }));
        jPanel19.add(jComboBox2, new java.awt.GridBagConstraints());

        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Número da mesa");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel19.add(jTextField4, new java.awt.GridBagConstraints());

        jTextField5.setForeground(new java.awt.Color(204, 204, 204));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Quantidade a remover");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel19.add(jTextField5, new java.awt.GridBagConstraints());

        jPanel10.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(204, 204, 255));

        jButton3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton3);

        jPanel10.add(jPanel20);

        jPanel3.add(jPanel10, "card4");

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jPanel21.setBackground(new java.awt.Color(204, 204, 255));
        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setText("Receber Pagamento");
        jPanel21.add(jLabel25);

        jPanel11.add(jPanel21);

        jPanel30.setBackground(new java.awt.Color(204, 204, 255));
        jPanel30.setLayout(new java.awt.GridBagLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 0));
        jLabel37.setText("Mesa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 102, 0, 0);
        jPanel30.add(jLabel37, gridBagConstraints);

        jTextField7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 85, 34, 0);
        jPanel30.add(jTextField7, gridBagConstraints);

        jButton6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton6.setText("Mostrar Valor!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 44, 0, 121);
        jPanel30.add(jButton6, gridBagConstraints);

        jPanel11.add(jPanel30);

        jPanel23.setBackground(new java.awt.Color(204, 204, 255));
        jPanel23.setLayout(new java.awt.GridLayout(1, 4));

        jLabel26.setBackground(new java.awt.Color(204, 204, 255));
        jLabel26.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 0));
        jLabel26.setText("Valor Total");
        jPanel23.add(jLabel26);

        jLabel27.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 0));
        jLabel27.setText("R$");
        jPanel23.add(jLabel27);
        jPanel23.add(jLabel40);

        jPanel11.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(204, 204, 255));
        jPanel24.setMinimumSize(new java.awt.Dimension(291, 72));
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel29.setText("                                              ");
        jPanel24.add(jLabel29);

        jButton4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton4.setText("Confirmar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton4);

        jPanel11.add(jPanel24);

        jPanel3.add(jPanel11, "card5");

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setBackground(new java.awt.Color(204, 204, 255));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 0));
        jLabel35.setText("Fechar uma comanda");
        jLabel35.setToolTipText("");
        jPanel17.add(jLabel35);

        jPanel12.add(jPanel17);

        jPanel25.setBackground(new java.awt.Color(204, 204, 255));
        jPanel25.setLayout(new java.awt.GridLayout(2, 3));
        jPanel25.add(jLabel21);

        jLabel18.setForeground(new java.awt.Color(0, 153, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Mesa da comanda");
        jPanel25.add(jLabel18);
        jPanel25.add(jLabel24);
        jPanel25.add(jLabel23);

        jTextField6.setForeground(new java.awt.Color(204, 204, 204));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Mesa da comanda a excluir");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jPanel25.add(jTextField6);
        jPanel25.add(jLabel28);

        jPanel12.add(jPanel25);

        jPanel26.setBackground(new java.awt.Color(204, 204, 255));

        jButton5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton5.setText("Fechar comanda");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton5);

        jPanel12.add(jPanel26);

        jPanel3.add(jPanel12, "card6");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel13, "card7");

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jLabel10.setText("Log out");
        jLabel10.setToolTipText("E.g.: Icon made by Smashicons from www.flaticon.com ");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 309, 0, 27);
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant-cutlery-circular-symbol-of-a-spoon-and-a-fork-in-a-circle.png"))); // NOI18N
        jLabel36.setToolTipText("E.g.: Icon made by Freepik from www.flaticon.com ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(jLabel36, gridBagConstraints);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //algum problema aqui
        Cliente cli = new Cliente(jTextField1.getText(), Integer.parseInt(jTextField2.getText()));
        Comanda com = new Comanda(cli, mini.getGU().getUsuarioLogado());
        if (mini.getGC().getComandas().containsKey(cli.getMesa())) {
            if (mini.getGC().getComandas().get(cli.getMesa()).getCliente().getMesa() == Integer.parseInt(jTextField2.getText())) {
                JOptionPane.showMessageDialog(this, "Comanda já criada");
            }
        } else {
            mini.getGC().addNewOrUpdatedComanda(com);
            mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
            JOptionPane.showMessageDialog(this, "Comanda adicionada com sucesso", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
        try {
            new MenuLogin().setVisible(true);
        } catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jTextField3.setText("");
        jTextField3.setForeground(Color.black);
        jTextField3.setFont(new Font("Dialog", Font.PLAIN, 36));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
        jTextField4.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        jTextField6.setText("");
        jTextField6.setForeground(Color.BLACK);
        jTextField6.setFont(new Font("Dialog", Font.PLAIN, 36));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText("");
        jTextField5.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        SetarParaOPadrao();
        cardlayout.show(jPanel3, "card2");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        SetarParaOPadrao();
        cardlayout.show(jPanel3, "card3");

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if (mini.getLastLogged().isGerente()) {
            SetarParaOPadrao();
            cardlayout.show(jPanel3, "card4");
        } else {
            JOptionPane.showMessageDialog(this, "Apenas um gerente pode acessar essa seção", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if (mini.getLastLogged().isGerente()) {
            SetarParaOPadrao();
            cardlayout.show(jPanel3, "card5");
        } else {
            JOptionPane.showMessageDialog(this, "Apenas um gerente pode acessar essa seção", "Erro!", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if (mini.getLastLogged().isGerente()) {
            SetarParaOPadrao();
            cardlayout.show(jPanel3, "card6");
        } else {
            JOptionPane.showMessageDialog(this, "Apenas um gerente pode acessar essa seção", "Erro!", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        SetarParaOPadrao();
        cardlayout.show(jPanel3, "card7");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
        jTextField1.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
        jTextField2.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String item = (String) jComboBox1.getSelectedItem();
        Comanda com;
        if (Integer.parseInt(jTextField8.getText()) > 0) {
            if (mini.getGC().getComandas().get(Integer.parseInt(jTextField3.getText())) != null) {
                com = mini.getGC().getComandas().get(Integer.parseInt(jTextField3.getText()));
                if (com.isComandaAberta()) {
                    ComboboxOptionSelect(item, com);
                } else {
                    JOptionPane.showMessageDialog(this, "Comanda está fechada!", "Oops", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mesa inexistênte", "Ooops!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Deve haver pelo menos 1 pedido");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void ComboboxOptionSelect(String item, Comanda com) {
        switch (item) {
            case "Selecione um pedido":
                break;
            case "X-Burger":
                CasoXburger(com, item);
                break;
            case "X-Salada":
                CasoXsalada(com, item);
                break;
            case "Iscas de Frango":
                CasoIscasdeFrango(com, item);
                break;
            case "Cerveja":
                CasoCerveja(com, item);
                break;
            case "Suco":
                CasoSuco(com, item);
                break;
            case "Couvert artístico":
                CasoCouvert(com, item);
                break;
        }
    }

    private void CasoXburger(Comanda com, String item) {
        com.addPedido(new Produto(item, jTextPane1.getText(), Integer.parseInt(jTextField8.getText()), 2.5f, 0.5f, 0.3f));
        mini.getGC().addNewOrUpdatedComanda(com);
        mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
        JOptionPane.showMessageDialog(this, "Pedido adicionado");
    }

    private void CasoXsalada(Comanda com, String item) {
        com.addPedido(new Produto(item, jTextPane1.getText(), Integer.parseInt(jTextField8.getText()), 2.5f, 0.5f, 0.3f));
        mini.getGC().addNewOrUpdatedComanda(com);
        mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
        JOptionPane.showMessageDialog(this, "Pedido adicionado");

    }

    private void CasoIscasdeFrango(Comanda com, String item) {
        com.addPedido(new Produto(item, jTextPane1.getText(), Integer.parseInt(jTextField8.getText()), 5.5f, 0.7f, 0.1f));
        mini.getGC().addNewOrUpdatedComanda(com);
        mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
        JOptionPane.showMessageDialog(this, "Pedido adicionado");
    }

    private void CasoCerveja(Comanda com, String item) {
        com.addPedido(new Produto(item, jTextPane1.getText(), Integer.parseInt(jTextField8.getText()), 2.5f, 1, 0.3f));
        mini.getGC().addNewOrUpdatedComanda(com);
        mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
        JOptionPane.showMessageDialog(this, "Pedido adicionado");
    }

    private void CasoSuco(Comanda com, String item) {
        com.addPedido(new Produto(item, jTextPane1.getText(), Integer.parseInt(jTextField8.getText()), 0f, 1, 0.0f));
        mini.getGC().addNewOrUpdatedComanda(com);
        mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
        JOptionPane.showMessageDialog(this, "Pedido adicionado");
    }

    private void CasoCouvert(Comanda com, String item) {
        com.addPedido(new Service(Integer.parseInt(jTextField8.getText()), jTextPane1.getText(), item, 10));
        mini.getGC().addNewOrUpdatedComanda(com);
        mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (mini.getGC().getComandas().containsKey(Integer.parseInt(jTextField4.getText()))) {
            Comanda comanda = mini.getGC().getComandas().get(Integer.parseInt(jTextField4.getText()));
            int qntPedidoXYZ = ContarQntsPedidosTem(comanda);
            if (comanda.isComandaAberta()) {
                if (qntPedidoXYZ >= Integer.parseInt(jTextField5.getText())) {
                    DiminuirQuantidade(comanda);
                } else {
                    JOptionPane.showMessageDialog(this, "Você possui essa quantidade de pedidos");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Essa mesa está com a comanda fechada");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Essa mesa não possui comanda");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        switch (jComboBox1.getSelectedItem().toString()) {
            case "X-Burger":
                jTextPane1.setText("Pão, carne, queijo, presunto");
                break;
            case "X-Salada":
                jTextPane1.setText("Pão, carne, queijo, salada");
                break;
            case "Iscas de Frango":
                jTextPane1.setText("Iscas de frango a milanesa picado");
                break;
            case "Cerveja":
                jTextPane1.setText("Álcool, gás e cevada");
                break;
            case "Suco":
                jTextPane1.setText("Suco de fruta");
                break;
            case "Couvert artístico":
                jTextPane1.setText("Couvert artístico. O cliente pagará gostando ou não");
                break;

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int mesa = Integer.parseInt(jTextField7.getText());
        Comanda com = mini.getGC().getComandas().get(mesa);
        jLabel27.setText(String.format("R$ %.2f", com.getValorTotal()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (mini.getGC().getComandas().get(Integer.parseInt(jTextField7.getText())).isComandaAberta()) {
            mini.getGC().getComandas().get(Integer.parseInt(jTextField7.getText())).setValorTotal(0);
            jLabel27.setText("R$ 00.00");
        } else {
            JOptionPane.showMessageDialog(this, "Esse comanda não está mais ativa");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (mini.getGC().getComandas().get(Integer.parseInt(jTextField6.getText())).isComandaAberta()) {
            mini.getGC().getComandas().get(Integer.parseInt(jTextField6.getText())).fecharComanda();
            JOptionPane.showMessageDialog(this, "Comanda fechada com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Comanda anteriormente fechada");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    private void DiminuirQuantidade(Comanda comanda) {
        int i = 0;
        double valordeUm = 1;
        Iterator ite = comanda.getPedidos().iterator();
        while (i < Integer.parseInt(jTextField5.getText())) {
            Pedido element = (Pedido) ite.next();
            if (element.getNome() == jComboBox2.getSelectedItem()) {
                int quant = element.getQuantidade();
                valordeUm = element.getValor(); // if getqntd > 1 add!
                if (quant <= Integer.parseInt(jTextField5.getText())) {
                    while (quant > 0 && quant <= Integer.parseInt(jTextField5.getText())) {
                        element.setQuantidade(element.getQuantidade() - 1);
                        quant--;
                        i++;
                        if (element.getQuantidade() == 0) {
                            ite.remove();
                        }
                    }
                } else {
                    do {
                        element.setQuantidade(element.getQuantidade() - 1);
                        i++;
                    } while (quant - Integer.parseInt(jTextField5.getText()) < element.getQuantidade());
                }
            }
        }
        if (i == Integer.parseInt(jTextField5.getText())) {
            JOptionPane.showMessageDialog(this, "Pedidos excluídos com sucesso");
            mini.getGC().getComandas().get(Integer.parseInt(jTextField4.getText())).AtualizarValorTotal(-(i * valordeUm));
            comanda=mini.getGC().getComandas().get(Integer.parseInt(jTextField4.getText()));
            mini.getGC().addNewOrUpdatedComanda(comanda);
            mini.getP().GravaEmDisco(mini.getGC(), "Comandas.bin");
        }
    }
    ///

    private int ContarQntsPedidosTem(Comanda com) {
        int total = 0;
        for (Pedido pe : com.getPedidos()) {
            if (pe.getNome().equals(jComboBox2.getSelectedItem())) {
                total += pe.getQuantidade();
            }
        }
        return total;
    }

    private void SetarParaOPadrao() {
        jTextField1.setText("Nome do cliente");
        jTextField1.setForeground(Color.LIGHT_GRAY);
        jTextField2.setText("Mesa do cliente");
        jTextField2.setForeground(Color.LIGHT_GRAY);
        jTextField3.setText("Número da mesa");
        jTextField3.setForeground(Color.LIGHT_GRAY);
        jTextField3.setFont(new Font("Tahoma", Font.PLAIN, 11));
        jTextField8.setText("");
        jTextPane1.setText("");
        jTextField4.setText("Número da mesa");
        jTextField4.setForeground(Color.LIGHT_GRAY);
        jTextField5.setText("Quantidade a remover");
        jTextField5.setForeground(Color.LIGHT_GRAY);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField6.setText("Mesa da comanda a excluir");
        jTextField6.setFont(new Font("Tahoma", Font.PLAIN, 11));
        jTextField6.setForeground(Color.LIGHT_GRAY);
        jTextField7.setText("");
        jLabel27.setText("R$");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnhancedMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnhancedMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnhancedMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnhancedMenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new EnhancedMenuOpcoes().setVisible(true);
                } catch (IOException ex) {
                    //fuck this
                } catch (ClassNotFoundException ex) {
                    //and this
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
